### ISSUE TITLE
Error message/link for duplicate email

### ISSUE THREAD

**Issue by emerywebster** [crowdfavorite/wp-mailchimp#30]
From user:

When you enter an email address that is already registered, you get an error message with a link to "Update your preferences"

The clickable link is incorrect. In the routine "mailchimp.php", line 1417 (look for the processing of error code 214), and has towards the end ::

    http://$username.$dc.list-manage.com/....

whereas it should just be ::

    http://$dc.list-manage.com/...

There is also a call to a "<a name" tag that is obviously coded AFTER the error message. Thus unless the user scrolls up, they wont see it.

**Comment by kidfiction** [comment]
This should be fixed with 8669ef2b7eca9f6c40239abfa18416becefca45a
